"use client";
import { useMemo, useState } from "react";
import { AdminDishThumbnail } from "@/components/admin/AdminDishThumbnail";
import { AdminDishAvailabilityControl } from "@/components/admin/AdminDishAvailabilityControl";
import { AdminStatusBadge, AdminToast } from "@/components/admin/system/AdminPrimitives";
import type { AdminMenuDish } from "@/lib/admin/menuReadiness";
import { resolveAvailability, type AvailabilityFeedback, type AvailabilityOverride } from "./availabilityMutation";
import styles from "./AdminAvailability.module.css";

type Filter="all"|"available"|"unavailable";
const filters:Array<{id:Filter;label:string}>=[{id:"all",label:"Tous"},{id:"available",label:"Disponibles"},{id:"unavailable",label:"Indisponibles"}];
export function AdminAvailabilityList({dishes}:{dishes:AdminMenuDish[]}){
 const [filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState(""),[availability,setAvailability]=useState<Record<string,AvailabilityOverride>>({}),[feedback,setFeedback]=useState<AvailabilityFeedback>({tone:null,message:null});
 const current=useMemo(()=>dishes.map(d=>({...d,available:resolveAvailability(d.available,availability[d.id])})),[availability,dishes]);
 const available=current.filter(d=>d.available).length,visible=current.filter(d=>(filter==="all"||(filter==="available"?d.available:!d.available))&&d.name.toLocaleLowerCase("fr").includes(query.trim().toLocaleLowerCase("fr")));
 return <section className={styles.page} aria-labelledby="availability-title"><header className={styles.summary}><div><h2 id="availability-title">Disponibilité des plats</h2><p>Gérez simplement la disponibilité de chaque plat sur votre menu.</p></div><div className={styles.metrics}><article><span>Total des plats</span><strong>{current.length}</strong></article><article><span>Disponibles</span><strong>{available}</strong></article><article><span>Indisponibles</span><strong>{current.length-available}</strong></article></div></header><div className={styles.controls}><label><span className="sr-only">Rechercher un plat</span><input type="search" placeholder="Rechercher un plat…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className={styles.filters} aria-label="Filtrer les plats">{filters.map(item=><button key={item.id} type="button" aria-pressed={filter===item.id} onClick={()=>setFilter(item.id)}>{item.label}</button>)}</div></div><div className={styles.list}>{visible.map(dish=><article className={styles.row} key={dish.id} data-available={dish.available}><AdminDishThumbnail name={dish.name} thumbnailUrl={dish.thumbnailUrl} imageUrl={dish.imageUrl}/><div className={styles.identity}><h3>{dish.name}</h3><p>{dish.category}</p></div><p className={styles.price}>{dish.priceLabel}</p><AdminStatusBadge tone={dish.available?"available":"unavailable"}>{dish.available?"Disponible":"Indisponible"}</AdminStatusBadge><AdminDishAvailabilityControl key={`${dish.id}:${dish.available}`} dishId={dish.id} dishName={dish.name} initialAvailable={dish.available} onAvailabilityChange={value=>setAvailability(state=>({...state,[dish.id]:{base:dish.available,value}}))} onFeedback={setFeedback}/></article>)}</div><p className="sr-only" aria-live="polite">{visible.length} résultat{visible.length>1?"s":""} affiché{visible.length>1?"s":""}.</p>{visible.length===0?<p className={styles.empty} role="status">Aucun plat ne correspond à cette recherche.</p>:null}{feedback.message?<AdminToast tone={feedback.tone==="error"?"error":"success"}>{feedback.message}</AdminToast>:null}</section>;
}
