export const site = "https://www.vistaire.ca";
export const collections = [
  {
    id: "acrylique",
    name: "Acrylique",
    price: 2000,
    extra: 40,
    image: "support-acrylique",
    description:
      "Une présence légère et lumineuse. Le support laisse toute la place à votre identité.",
  },
  {
    id: "sculpte",
    name: "Sculpté",
    price: 2050,
    extra: 45,
    image: "support-sculpte",
    description:
      "Une forme expressive, pensée pour prolonger le caractère du lieu.",
  },
  {
    id: "carre",
    name: "Carré",
    price: 2100,
    extra: 55,
    image: "support-carre",
    description:
      "Des lignes nettes et une silhouette discrète, naturellement à sa place à table.",
  },
  {
    id: "signature",
    name: "Signature",
    price: 2200,
    extra: 55,
    image: "support-signature",
    description:
      "Une pièce de caractère, pour une expérience qui porte votre signature.",
  },
];
export const dishes = [
  {
    id: "homard",
    iosModel: "/immersive-assets/ar/homard.usdz",
    arWidthMeters: 0.26,
    label: "Homard bleu",
    name: "Homard bleu",
    fullName: "Homard bleu, bisque corsée & fenouil",
    price: 104,
    image: "homard",
    category: "Plats signatures",
    restaurant: "Maison Élyse",
    description:
      "La chair délicate du homard rencontre une bisque profonde et les notes anisées du fenouil.",
    model: true,
    allergens: "Crustacés, lait",
  },
  {
    id: "souffle",
    iosModel: "/immersive-assets/ar/souffle.usdz",
    arWidthMeters: 0.12,
    label: "Soufflé chocolat",
    name: "Soufflé chocolat",
    fullName: "Soufflé tiède au chocolat grand cru",
    price: 28,
    image: "souffle",
    category: "Desserts",
    restaurant: "Maison Élyse",
    description:
      "Un soufflé aérien au chocolat intense, un cœur coulant et une glace délicatement parfumée à la vanille.",
    model: true,
    allergens: "Gluten / céréales, produits laitiers, œufs",
  },
  {
    id: "huitres",
    iosModel: "/immersive-assets/ar/huitres.usdz",
    arWidthMeters: 0.1202,
    label: "Huîtres au kombu",
    name: "Huîtres au kombu",
    fullName: "Huîtres tièdes au kombu",
    price: 20,
    image: "huitres",
    category: "Entrées",
    restaurant: "Sauge Noire",
    description:
      "Trois huîtres tièdes au kombu sont servies avec de la pomme verte, du beurre noisette et une huile de livèche.",
    model: "/immersive-assets/dishes/huitres.glb",
    allergens: "Mollusques, produits laitiers",
  },
  {
    id: "sushi",
    iosModel: "/immersive-assets/ar/sushi.usdz",
    arWidthMeters: 0.2602,
    label: "Plateau sushi Horizon",
    name: "Plateau sushi Horizon",
    fullName: "Plateau sushi Horizon",
    price: 30.99,
    image: "sushi",
    category: "Voyage à l’assiette",
    restaurant: "Trouvable",
    description: "Une présentation à découvrir sous tous les angles.",
    model: "/immersive-assets/dishes/sushi.glb",
    allergens: null,
  },
  {
    id: "chocolat-fume",
    iosModel: "/immersive-assets/ar/chocolat-fume.usdz",
    arWidthMeters: 0.12,
    label: "Chocolat fumé",
    name: "Chocolat fumé",
    fullName: "Chocolat fumé",
    price: 15,
    image: "chocolat-fume",
    category: "Desserts",
    restaurant: "Sauge Noire",
    description:
      "Le chocolat noir à 70 % est servi avec de l’huile d’olive, du sel fumé et du grué de cacao.",
    model: "/immersive-assets/dishes/chocolat-fume.glb",
    allergens: null,
  },
  {
    id: "poutine",
    iosModel: "/immersive-assets/ar/poutine.usdz",
    arWidthMeters: 0.18,
    label: "Poutine du Vieux-Montréal",
    name: "Poutine du Vieux-Montréal",
    fullName: "Poutine du Vieux-Montréal",
    price: 16.99,
    image: "poutine",
    category: "Classiques réinventés",
    restaurant: "Trouvable",
    description: "Une présentation à découvrir sous tous les angles.",
    model: "/immersive-assets/dishes/poutine.glb",
    allergens: null,
  },
  {
    id: "burger",
    iosModel: "/immersive-assets/ar/burger.usdz",
    arWidthMeters: 0.1549,
    label: "Burger signature",
    name: "Burger signature",
    fullName: "Burger signature maison",
    price: 22.99,
    image: "burger",
    category: "Classiques réinventés",
    restaurant: "Trouvable",
    description: "Une présentation à découvrir sous tous les angles.",
    model: "/immersive-assets/dishes/burger.glb",
    allergens: null,
  },
];
export const experiences = [
  {
    id: "maison-elyse",
    name: "Maison Élyse",
    tag: "Éditoriale & gastronomique",
    image: "experience-maison-elyse",
    description:
      "Une carte lumineuse, des compositions soignées, une cuisine qui se raconte.",
  },
  {
    id: "trouvable",
    name: "Trouvable",
    tag: "Moderne & interactive",
    image: "experience-trouvable",
    description:
      "Une navigation directe et des plats qui prennent toute leur place.",
  },
  {
    id: "sauge-noire",
    name: "Sauge Noire",
    tag: "Signature & immersive",
    image: "experience-sauge-noire",
    description:
      "Un univers botanique, sombre et singulier. La carte devient une expérience.",
  },
];
export const chapters = [
  ["hero", "Introduction", 100],
  ["ai", "Du scan à la carte", 220],
  ["wearable", "Pensé pour le mobile", 180],
  ["features", "Chaque détail compte", 280],
  ["encryption", "Votre identité", 180],
  ["grip", "Plats en 3D", 220],
  ["sustainability", "Une carte vivante", 180],
  ["testimonies", "Trois identités", 160],
  ["social-content", "À table", 300],
  ["product", "Les collections", 220],
  ["open-weight", "Tarifs et accompagnement", 130],
  ["footer", "Contact", 110],
];
export const money = (n) =>
  new Intl.NumberFormat("fr-CA", { maximumFractionDigits: 0 }).format(n);
