import type { AdminObservationWindow } from "./dashboardRange.ts";
import { addComparisonEvidence, type AdminRawMetric } from "./analyticsEvidence.ts";
import { buildAdminAnalyticsPanels, isPrivacySafeAdminSearchTerm, type AdminAnalyticsPanels, type AdminAnalyticsPanelScope } from "./analyticsPresentation.ts";
import { ADMIN_ANALYTICS_THRESHOLDS } from "./analyticsThresholds.ts";

type EventRow = Record<string, unknown>;
type Ranked = { slug: string; count: number };
export type AdminMetricSeriesId = "menuOpened" | "dishOpened" | "searches" | "immersive";
export type AdminMetricPoint = { bucket: string; value: number; timestampLabel: string };
export type AdminMetricSeries = { id: AdminMetricSeriesId; current: AdminMetricPoint[]; previous: AdminMetricPoint[] };
export type AdminEvidence = { label: string; value: string | number };
export type AdminAnalyticsState =
 | { kind:"real"; completeness:"complete"|"limited-sample"; observationWindow:AdminObservationWindow; panels:AdminAnalyticsPanels; lastUpdatedAt:string|null; freshness:"fresh"|"delayed"|"stale"; coverage:{menuOpened:boolean;dishOpened:boolean}; metrics:ReturnType<typeof addComparisonEvidence>[]; metricSeries:Record<AdminMetricSeriesId,AdminMetricSeries>; activitySeries:{bucket:string;count:number}[]; categoryBreakdown:Ranked[]; topDishes:Ranked[]; searches:{term:string;count:number}[]; immersive:{name:string;count:number}[]; funnel:{kind:"unsupported"}|{kind:"measured";sessions:number;dishOpened:number;rate:number}; comparison:null|Record<string,unknown> }
 | { kind:"insufficient"; reason:"no-relevant-events"|"sample-too-small"|"instrumentation-unproven"; completeness:"complete"|"limited-sample"; observationWindow:AdminObservationWindow; availableEvidence:AdminEvidence[]; missingEvidence:string[] }
 | { kind:"unavailable"; reason:"configuration"|"database"|"query"; completeness:"truncated"|"partial-source"; title:string; explanation:string; retryable:boolean };
export type AdminAnalyticsInput={observationWindow:AdminObservationWindow;events?:EventRow[];previousEvents?:EventRow[];analyticsScope?:AdminAnalyticsPanelScope;selectedMenuCategorySlugs?:string[];selectedMenuCategories?:{slug:string;label:string}[];availableDishCount?:number;instrumentationProven?:boolean;eventCount?:number;databaseError?:boolean;queryError?:boolean;truncated?:boolean;partialSource?:boolean;lastUpdatedAt?:string|null;metrics?:AdminRawMetric[]};
const text=(row:EventRow,key:string)=>typeof row[key]==="string"?(row[key] as string):"";
const counts=(values:string[])=>[...values.reduce((map,value)=>value?map.set(value,(map.get(value)??0)+1):map,new Map<string,number>())].map(([slug,count])=>({slug,count})).sort((a,b)=>b.count-a.count||a.slug.localeCompare(b.slug));
const pointLabel=(timestamp:number)=>new Intl.DateTimeFormat("fr-CA",{day:"numeric",month:"long",timeZone:"UTC"}).format(new Date(timestamp));
const seriesPoints=(events:EventRow[],names:Set<string>,startIso:string,endIso:string,bucketCount:number):AdminMetricPoint[]=>{
 const start=Date.parse(startIso); const end=Date.parse(endIso); if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return[]; const duration=(end-start)/bucketCount; const values=Array.from({length:bucketCount},()=>0);
 for(const row of events){if(!names.has(text(row,"event_name")))continue;const timestamp=Date.parse(text(row,"created_at"));const index=Math.floor((timestamp-start)/duration);if(Number.isFinite(timestamp)&&index>=0&&index<bucketCount)values[index]++;}
 return values.map((value,index)=>{const timestamp=start+index*duration;return{bucket:new Date(timestamp).toISOString().slice(0,10),value,timestampLabel:pointLabel(timestamp)}});
};
const metricSeries=(current:EventRow[],previous:EventRow[],window:AdminObservationWindow):Record<AdminMetricSeriesId,AdminMetricSeries>=>{
 const bucketCount=window.range==="today-utc"?1:window.range==="7d"?7:30;
 return Object.fromEntries(([ ["menuOpened",["menu_opened"]], ["dishOpened",["dish_opened"]], ["searches",["search_used"]], ["immersive",["dish_3d_clicked","dish_ar_clicked"]] ] as const).map(([id,names])=>[id,{id,current:seriesPoints(current,new Set(names),window.startInclusive,window.endExclusive,bucketCount),previous:seriesPoints(previous,new Set(names),window.comparisonStartInclusive,window.comparisonEndExclusive,bucketCount)}])) as Record<AdminMetricSeriesId,AdminMetricSeries>;
};
export function buildAdminAnalyticsState(input:AdminAnalyticsInput):AdminAnalyticsState{
 if(input.databaseError||input.queryError||input.truncated||input.partialSource)return{kind:"unavailable",reason:input.databaseError?"database":"query",completeness:input.truncated?"truncated":"partial-source",title:"Données indisponibles",explanation:"La lecture est incomplète.",retryable:true};
 const events=input.events??[]; const names=events.map(row=>text(row,"event_name"));
 const menuCount=names.filter(name=>name==="menu_opened").length; const dishCount=names.filter(name=>name==="dish_opened").length;
 const proven=input.events?menuCount>0&&dishCount>0:Boolean(input.instrumentationProven); const relevant=input.events?menuCount+dishCount:(input.eventCount??0);
 if(!proven||relevant===0||relevant<ADMIN_ANALYTICS_THRESHOLDS.minimumRelevantEvents)return{kind:"insufficient",reason:!proven?"instrumentation-unproven":relevant===0?"no-relevant-events":"sample-too-small",completeness:relevant>0?"limited-sample":"complete",observationWindow:input.observationWindow,availableEvidence:[],missingEvidence:!proven?["menu_opened","dish_opened"]:[]};
 const buckets=counts(events.map(row=>text(row,"created_at").slice(0,10))).map(({slug,count})=>({bucket:slug,count})).sort((a,b)=>a.bucket.localeCompare(b.bucket));
 const rankedDishes=dishCount>=ADMIN_ANALYTICS_THRESHOLDS.minimumRankedDishEvents?counts(events.filter(row=>text(row,"event_name")==="dish_opened").map(row=>text(row,"dish_slug"))).filter(item=>item.count>=ADMIN_ANALYTICS_THRESHOLDS.minimumRankedItemCount):[];
 const categories=dishCount>=ADMIN_ANALYTICS_THRESHOLDS.minimumRankedDishEvents?counts(events.filter(row=>text(row,"event_name")==="dish_opened").map(row=>text(row,"category_slug"))).filter(item=>item.count>=ADMIN_ANALYTICS_THRESHOLDS.minimumRankedItemCount):[];
 const searchCounts=counts(events.filter(row=>text(row,"event_name")==="search_used").map(row=>text(row,"search_query").trim().toLocaleLowerCase("fr-CA")).filter(isPrivacySafeAdminSearchTerm)).filter(item=>item.count>=ADMIN_ANALYTICS_THRESHOLDS.minimumSearchTermCount).map(({slug,count})=>({term:slug,count}));
 const immersive=["dish_3d_clicked","dish_ar_clicked"].map(name=>({name,count:names.filter(value=>value===name).length}));
 const sessions=new Map<string,{menu:number;dish:number}>(); events.forEach((row,index)=>{const id=text(row,"session_id");if(!id)return;const state=sessions.get(id)??{menu:Infinity,dish:Infinity};if(text(row,"event_name")==="menu_opened")state.menu=Math.min(state.menu,index);if(text(row,"event_name")==="dish_opened")state.dish=Math.min(state.dish,index);sessions.set(id,state)}); const qualifying=[...sessions.values()].filter(s=>Number.isFinite(s.menu)); const converted=qualifying.filter(s=>Number.isFinite(s.dish)&&s.menu<s.dish).length;
 const last=input.lastUpdatedAt??events.map(row=>text(row,"created_at")).sort().at(-1)??null; const age=last?Date.now()-new Date(last).getTime():Infinity;
 const currentDurationMs=Date.parse(input.observationWindow.endExclusive)-Date.parse(input.observationWindow.startInclusive); const previousDurationMs=Date.parse(input.observationWindow.comparisonEndExclusive)-Date.parse(input.observationWindow.comparisonStartInclusive);
 const previous=input.previousEvents??[]; const previousNames=previous.map(row=>text(row,"event_name"));
 const rawMetrics=input.metrics??[{id:"menu-opens",value:menuCount,baseline:previousNames.filter(name=>name==="menu_opened").length},{id:"dish-opens",value:dishCount,baseline:previousNames.filter(name=>name==="dish_opened").length},{id:"searches",value:names.filter(name=>name==="search_used").length,baseline:previousNames.filter(name=>name==="search_used").length},{id:"immersive",value:names.filter(name=>name==="dish_3d_clicked"||name==="dish_ar_clicked").length,baseline:previousNames.filter(name=>name==="dish_3d_clicked"||name==="dish_ar_clicked").length},{id:"available-dishes",value:input.availableDishCount??0}];
 const bucketCount=input.observationWindow.range==="today-utc"?1:input.observationWindow.range==="7d"?7:30;
 return{kind:"real",completeness:relevant<ADMIN_ANALYTICS_THRESHOLDS.minimumRankedDishEvents?"limited-sample":"complete",observationWindow:input.observationWindow,panels:buildAdminAnalyticsPanels({currentEvents:events,previousEvents:previous,currentDurationMs,previousDurationMs,currentPeriod:{startInclusive:input.observationWindow.startInclusive,endExclusive:input.observationWindow.endExclusive,bucketCount},previousPeriod:{startInclusive:input.observationWindow.comparisonStartInclusive,endExclusive:input.observationWindow.comparisonEndExclusive,bucketCount},currentScope:input.analyticsScope??null,previousScope:input.analyticsScope??null,selectedMenuCategorySlugs:input.selectedMenuCategorySlugs,selectedMenuCategories:input.selectedMenuCategories}),lastUpdatedAt:last,freshness:age<=3600000?"fresh":age<=86400000?"delayed":"stale",coverage:{menuOpened:menuCount>0||proven,dishOpened:dishCount>0||proven},metrics:rawMetrics.map(addComparisonEvidence),metricSeries:metricSeries(events,previous,input.observationWindow),activitySeries:buckets,categoryBreakdown:categories,topDishes:rankedDishes,searches:searchCounts,immersive,funnel:qualifying.length>=ADMIN_ANALYTICS_THRESHOLDS.minimumFunnelSessions?{kind:"measured",sessions:qualifying.length,dishOpened:converted,rate:converted/qualifying.length}:{kind:"unsupported"},comparison:null};
}
