import { AdminAnalyticsPanel } from "./AdminAnalyticsPanel";
import { AdminDishWorklist } from "./AdminDishWorklist";
import { AdminMenuActions } from "./AdminMenuActions";
import type { TargetAnalyticsState } from "./adminDashboardViewModel";
import styles from "./AdminDashboard.module.css";
import type { AdminDashboardData } from "@/lib/admin/dashboardData";

type Range="today-utc"|"7d"|"30d";
type ViewData={restaurant:{name:string;publicMenuPath:string|null};menu:{dishes:AdminDashboardData["dishes"];readiness:AdminDashboardData["readiness"]};analytics:TargetAnalyticsState};
const rangeLabel=(range:Range)=>range==="today-utc"?"Aujourd’hui — UTC":`Fenêtre glissante ${range==="7d"?"7 jours":"30 jours"} — UTC`;
function assertNever(value:never):never{throw new Error(`État inconnu: ${String(value)}`)}
// Temporary explicit legacy boundary. Delete when target AdminDashboardData lands.
function adaptDashboardData(data:AdminDashboardData):ViewData{const analytics:TargetAnalyticsState=(()=>{switch(data.analytics.kind){case"real":case"partial":return{kind:"insufficient",reason:"instrumentation-unproven",completeness:"limited-sample",observationWindow:{startedAt:"",endedAt:""},availableEvidence:[],missingEvidence:["Agrégation analytics cible requise"]};case"empty":return{kind:"insufficient",reason:"no-relevant-events",completeness:"complete",observationWindow:{startedAt:"",endedAt:""},availableEvidence:[],missingEvidence:[data.analytics.message]};case"preview":return{kind:"insufficient",reason:"instrumentation-unproven",completeness:"limited-sample",observationWindow:{startedAt:"",endedAt:""},availableEvidence:[],missingEvidence:[data.analytics.message]};default:return assertNever(data.analytics)}})();return{restaurant:{name:data.restaurant.name,publicMenuPath:data.restaurant.menuPath},menu:{dishes:data.dishes,readiness:data.readiness},analytics}}
export function AdminRestaurantDashboard({data,range}:{data:AdminDashboardData;range:Range}){const view=adaptDashboardData(data);const{readiness,dishes}=view.menu;return <main className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>Dashboard restaurant</p><h1>{view.restaurant.name}</h1><p className={styles.muted}>Gestion de la carte client</p></div>{view.restaurant.publicMenuPath?<AdminMenuActions menuPath={view.restaurant.publicMenuPath}/>:null}<nav aria-label="Sections du dashboard"><a href="#overview">Vue d’ensemble</a><a href="#dishes">Disponibilité des plats</a></nav></header><section className={styles.context} aria-label="Contexte des données"><div><strong>{rangeLabel(range)}</strong><span>Source : activité anonyme de production</span></div><p>Le fuseau horaire du restaurant n’est pas configuré. Les périodes sont affichées en UTC.</p><div className={styles.ranges}>{(["today-utc","7d","30d"] as Range[]).map(item=><a aria-current={item===range?"page":undefined} href={`?range=${item}`} key={item}>{item==="today-utc"?"Aujourd’hui":item}</a>)}</div></section><section id="overview" className={styles.section} aria-labelledby="overview-title"><div className={styles.sectionHead}><div><p className={styles.eyebrow}>État de la carte</p><h2 id="overview-title">Vue d’ensemble</h2></div><strong className={styles.score}>{readiness.score} % prêt</strong></div><div className={styles.metrics}><article><span>Plats</span><strong>{readiness.counts.dishes}</strong></article><article><span>Disponibles</span><strong>{readiness.counts.available}</strong></article><article><span>Photos prêtes</span><strong>{readiness.counts.withPhoto}</strong></article><article><span>Expériences 3D/AR</span><strong>{readiness.counts.withImmersive}</strong></article></div></section><section className={styles.section} aria-labelledby="evidence-title"><p className={styles.eyebrow}>Données d’activité</p><h2 id="evidence-title">Ce que les consultations permettent d’établir</h2><AdminAnalyticsPanel state={view.analytics}/></section><section id="dishes" className={styles.section}><AdminDishWorklist dishes={dishes}/></section></main>}
