import type { RestaurateurPreviewLocale, RestaurateurPreviewMetricId } from "./types";

const fr = {
  introBadge: "Aperçu restaurateur",
  h1: "Explorez le vrai fonctionnement du dashboard Vistaire.",
  lead: "Passez de la vue d’ensemble aux disponibilités et aux analyses dans une reproduction fidèle, conçue pour montrer le produit sans ouvrir le système privé.",
  demoLabel: "Données de démonstration",
  demoStatement: "Cette interface reproduit le fonctionnement du dashboard Vistaire avec des données fictives. Aucune donnée client n’est affichée ni modifiée.",
  appointment: "Prendre rendez-vous",
  sampleMenu: "Voir la carte exemple",
  dashboardEyebrow: "Vistaire · Démonstration",
  dashboardSubtitle: "Lecture synthétique de la carte et de son activité",
  tabsLabel: "Vues du dashboard de démonstration",
  tabs: { overview: "Vue d’ensemble", availability: "Disponibilités", insights: "Analyses" },
  periodsLabel: "Période analysée",
  periods: { "24h": "24 h", "7d": "7 jours", "30d": "30 jours" },
  metrics: {
    menuOpens: "Ouvertures du menu",
    dishOpens: "Consultations de plats",
    searches: "Recherches",
    immersive: "Interactions 3D/AR",
    available: "Plats disponibles"
  },
  trendAgainst: "vs période précédente",
  menuActivity: "Activité du menu",
  metricShown: "Métrique affichée",
  topDishes: "Top plats consultés",
  serviceActivity: "Activité par moment",
  categoryActivity: "Activité par catégorie",
  availabilityActivity: "Disponibilité des plats",
  available: "Disponible",
  unavailable: "Indisponible",
  availabilityEyebrow: "Disponibilités simulées",
  availabilityTitle: "État des plats",
  availabilityBody: "Recherchez un plat, filtrez la liste et simulez sa disponibilité. Rien n’est enregistré.",
  totalDishes: "Total des plats",
  availableDishes: "Disponibles",
  unavailableDishes: "Indisponibles",
  searchLabel: "Rechercher un plat",
  searchPlaceholder: "Nom ou catégorie",
  filtersLabel: "Filtrer les plats",
  filters: { all: "Tous", available: "Disponibles", unavailable: "Indisponibles" },
  noDishes: "Aucun plat ne correspond à cette recherche.",
  resultCount: "{count} plats affichés",
  resultCountOne: "1 plat affiché",
  toggleOn: "Rendre {dish} indisponible",
  toggleOff: "Rendre {dish} disponible",
  simulation: "Simulation. Ce changement n’est pas enregistré.",
  insightsKpis: "Indicateurs analytiques",
  activity: "Activité",
  activityTitle: "Activité du menu sur la période",
  comparison: "Comparaison",
  comparisonTitle: "Comparaison des périodes",
  comparisonDescription: "Total des ouvertures, consultations, recherches et interactions 3D/AR par repère",
  heatmap: "Moments d’activité",
  topSearches: "Top recherches",
  serviceTimes: "Moments de service",
  periodSummary: "Résumé de la période",
  keyInsights: "Insights clés",
  currentPeriod: "Période actuelle",
  previousPeriod: "Période précédente",
  interactions: "interactions",
  views: "consultations",
  searchesUnit: "recherches",
  exactValuesLabel: "Valeurs exactes",
  unitLabel: "Unité",
  markerLabel: "Repère",
  seriesLabel: "Série",
  valueLabel: "Valeur",
  stableActivity: "Activité stable sur cette période.",
  categoryDescription: "Chaque catégorie est identifiée par son libellé et sa valeur exacte.",
  categorySegment: "catégorie",
  segmentOf: "sur",
  heatScale: "Faible → Forte",
  heatDescription: "Intensité de faible à élevée, avec une valeur exacte par cellule.",
  utcDisclosure: "Heures affichées en UTC",
  unavailableComparison: "Comparaison indisponible.",
  incompatibleSeries: "Les séries doivent partager les mêmes repères.",
  delta: "Écart",
  qrBadge: "Carte exemple",
  qrTitle: "Scannez la carte publique de démonstration.",
  qrBody: "Le QR dirige uniquement vers la carte publique Vistaire. Il ne donne jamais accès au dashboard privé.",
  qrAria: "QR code vers la carte exemple Vistaire",
  finalTitle: "Reconnaissez le produit avant votre premier service.",
  finalBody: "Cette démonstration reprend les mêmes repères visuels et les mêmes vues métier que le dashboard restaurateur actuel, avec une fixture synthétique isolée."
} as const;

const en = {
  introBadge: "Restaurant preview",
  h1: "Explore how the Vistaire dashboard really works.",
  lead: "Move from Overview to Availability and Insights in a faithful product reproduction that demonstrates the experience without opening the private system.",
  demoLabel: "Demo data",
  demoStatement: "This interface reproduces how the Vistaire dashboard works using fictional data. No customer data is displayed or modified.",
  appointment: "Book a call",
  sampleMenu: "View sample menu",
  dashboardEyebrow: "Vistaire · Demonstration",
  dashboardSubtitle: "A concise reading of the menu and its activity",
  tabsLabel: "Demo dashboard views",
  tabs: { overview: "Overview", availability: "Availability", insights: "Insights" },
  periodsLabel: "Analysis period",
  periods: { "24h": "24 h", "7d": "7 days", "30d": "30 days" },
  metrics: {
    menuOpens: "Menu opens",
    dishOpens: "Dish views",
    searches: "Searches",
    immersive: "3D/AR interactions",
    available: "Available dishes"
  },
  trendAgainst: "vs previous period",
  menuActivity: "Menu activity",
  metricShown: "Metric shown",
  topDishes: "Top viewed dishes",
  serviceActivity: "Activity times",
  categoryActivity: "Activity by category",
  availabilityActivity: "Dish availability",
  available: "Available",
  unavailable: "Unavailable",
  availabilityEyebrow: "Simulated availability",
  availabilityTitle: "Dish status",
  availabilityBody: "Search, filter and simulate availability. Nothing is saved.",
  totalDishes: "Total dishes",
  availableDishes: "Available",
  unavailableDishes: "Unavailable",
  searchLabel: "Search dishes",
  searchPlaceholder: "Name or category",
  filtersLabel: "Filter dishes",
  filters: { all: "All", available: "Available", unavailable: "Unavailable" },
  noDishes: "No dishes match this search.",
  resultCount: "{count} dishes shown",
  resultCountOne: "1 dish shown",
  toggleOn: "Make {dish} unavailable",
  toggleOff: "Make {dish} available",
  simulation: "Simulation. This change is not saved.",
  insightsKpis: "Analytics indicators",
  activity: "Activity",
  activityTitle: "Menu activity over the period",
  comparison: "Comparison",
  comparisonTitle: "Period comparison",
  comparisonDescription: "Total menu opens, dish views, searches and 3D/AR interactions by marker",
  heatmap: "Activity times",
  topSearches: "Top searches",
  serviceTimes: "Service times",
  periodSummary: "Period summary",
  keyInsights: "Key insights",
  currentPeriod: "Current period",
  previousPeriod: "Previous period",
  interactions: "interactions",
  views: "views",
  searchesUnit: "searches",
  exactValuesLabel: "Exact values",
  unitLabel: "Unit",
  markerLabel: "Marker",
  seriesLabel: "Series",
  valueLabel: "Value",
  stableActivity: "Activity is stable over this period.",
  categoryDescription: "Each category is identified by its label and exact value.",
  categorySegment: "category",
  segmentOf: "of",
  heatScale: "Low → High",
  heatDescription: "Intensity from low to high, with an exact value for each cell.",
  utcDisclosure: "Times shown in UTC",
  unavailableComparison: "Comparison unavailable.",
  incompatibleSeries: "The series must share the same markers.",
  delta: "Difference",
  qrBadge: "Sample menu",
  qrTitle: "Scan the public sample menu.",
  qrBody: "The QR only opens the public Vistaire menu. It never provides access to the private dashboard.",
  qrAria: "QR code to the Vistaire sample menu",
  finalTitle: "Recognize the product before your first service.",
  finalBody: "This demonstration uses the same visual language and core views as the current restaurant dashboard, with an isolated synthetic fixture."
};

export const RESTAURATEUR_PREVIEW_COPY = { fr, en } as const;
export type RestaurateurPreviewCopy = (typeof RESTAURATEUR_PREVIEW_COPY)[RestaurateurPreviewLocale];

export const metricCopyKey = (id: RestaurateurPreviewMetricId) => id;
